# Generated by Django 6.1 on 2026-09-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('listing_image', models.ImageField(upload_to='brands/listing/')),
                ('listing_description', models.CharField(max_length=300)),
                ('hero_image', models.ImageField(upload_to='brands/hero/')),
                ('hero_description', models.TextField()),
                ('is_listed', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
