# Generated by Django 6.1 on 2026-09-25 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the fragrance category (e.g., Designer Fragrances).', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug generated automatically from name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short subtitle describing the category.', null=True)),
                ('offer_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for this category (0 to 99%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.0)])),
                ('is_listed', models.BooleanField(default=True, help_text='Controls if the category is Active/Listed in shop frontend.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag to preserve historical order records.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
    ]
